export const budgetOverviewCards = [
  {
    id: 'monthly-budget',
    type: 'budget',
    eyebrow: 'Total Monthly Budget',
    title: '$4,250.00',
    meta: '/ $5,000',
    progress: 85,
  },
  {
    id: 'critical-alerts',
    type: 'alert',
    eyebrow: 'Critical Alerts',
    title: '2 Over Limits',
    detail: 'Dining & Entertainment',
  },
  {
    id: 'suggested-savings',
    type: 'savings',
    eyebrow: 'AI Suggested Savings',
    title: 'Reduce Subscriptions by $24',
    detail: 'to reach your $2k savings goal.',
  },
]

export const budgetCategories = [
  {
    id: 'rent',
    icon: 'home',
    title: 'Rent & Housing',
    description: 'Fixed monthly property costs',
    tag: 'Fixed Cost',
    tagTone: 'neutral',
    progress: 100,
    progressTone: 'ink',
    sliderPosition: 56,
    limit: '$1,800',
  },
  {
    id: 'groceries',
    icon: 'basket',
    title: 'Groceries',
    description: 'Organic market & essentials',
    tag: 'Healthy',
    tagTone: 'accent',
    progress: 65,
    progressTone: 'accent',
    sliderPosition: 50,
    limit: '$600',
  },
  {
    id: 'dining',
    icon: 'dining',
    title: 'Dining Out',
    description: 'Fine dining & cocktails',
    tag: '92% Reached',
    tagTone: 'warning',
    progress: 92,
    progressTone: 'warning',
    sliderPosition: 48,
    limit: '$500',
    overlineValue: '$460 / $500',
  },
  {
    id: 'entertainment',
    icon: 'movie',
    title: 'Entertainment',
    description: 'Cinema, streaming & events',
    tag: 'Leisure',
    tagTone: 'neutral',
    progress: 42,
    progressTone: 'accent',
    sliderPosition: 44,
    limit: '$300',
  },
  {
    id: 'travel',
    icon: 'travel',
    title: 'Travel Fund',
    description: 'Vacation and exploration savings',
    tag: 'Savings Goal',
    tagTone: 'neutral',
    progress: 18,
    progressTone: 'accent',
    sliderPosition: 31,
    limit: '$1,200',
  },
]

export const categoriesFooterNote =
  'FINTRACK AI • BUDGET LEDGER ENGINE • ALLOCATION TRACKING ACTIVE'
